use_frameworks!

platform :ios, '8.0'

target 'JNKeyChainManager_Example' do
  pod 'JNKeyChainManager', :path => '../'

  target 'JNKeyChainManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
